name: CI

on: ["workflow_dispatch", "push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
              ${{ runner.os }}-nuget-
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Run the Cake script
        uses: cake-build/cake-action@v2
        with:
          verbosity: Diagnostic

      - name: Zip each folder in the build directory
        run: |
          for folder in ./build/*; do
            if [ -d "$folder" ]; then
              folder_name=$(basename "$folder")
              echo "Creating zip for folder: $folder_name"
              zip -r "./build/${folder_name}.zip" "$folder"
              echo "Created ./build/${folder_name}.zip"
            fi
          done

      - name: Create all-artifacts.zip
        run: |
          zip -r ./build/all-artifacts.zip ./build/*.zip

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build-Artifacts
          path: ./build/all-artifacts.zip
